name: databricks-cicd

on:
 push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      # Install databricks CLI 
      - name: Install databricks CLI
        run: |
         curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh  

      - name: Check DB CLI version
        run: databricks --version
      - name: Run databricks job "my-job"
        env:
          DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          JOB_NAME: 'my-job'
          WAIT_TIMEOUT: '20m0s'
        run: |
         JOB_ID=$(databricks jobs list | grep -w $JOB_NAME | awk -F ' ' '{print $1}')
         databricks jobs run-now $JOB_ID --timeout $WAIT_TIMEOUT  

      
