name: databricks-cicd

on:
 push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      # Install databricks CLI 
      - name: Install databricks CLI
        run: |
         curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh  

      - name: Databricks CLI version
        run: databricks --version
      - name: Run databricks job "my-job"
        env:
          DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          JOB_NAME: 'my-job'
          WAIT_TIMEOUT: '10m0s'
        run: databricks jobs list

      - name: Run a databricks notebook
        uses: databricks/run-notebook@v0.0.3
        with:
          new-cluster-json: >
           {
             "num_workers": 1,
             "spark_version": "10.4.x-scala2.12",
             "node_type_id": "m6i.large"
           }

        
      
