name: Run a notebook in databricks on PRs

on:
 push:

jobs:
 run-databricks-notebook:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repo
       uses: actions/checkout@v2
     - name: Install databricks CLI
       run: |
         curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh  

     - name: Databricks CLI version
       run: databricks --version
     - name: Run a databricks notebook
       uses: databricks/run-notebook@v0
       with:
         local-notebook-path: ./job.py
         databricks-host: https://dbc-4e21cf28-ef36.cloud.databricks.com
         databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
         new-cluster-json: >
           {
             "num_workers": 1,
             "spark_version": "10.4.x-scala2.12",
             "node_type_id": "m6i.large"
           }
