name: Run a notebook in databricks

on:
 push:

jobs:
 run-databricks-notebook:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repo
       uses: actions/checkout@v2
     - name: Run a databricks notebook
       uses: databricks/run-notebook@v0
       with:
         local-notebook-path: ./job.py
         DATABRICKS_HOST: https://dbc-4e21cf28-ef36.cloud.databricks.com
         DATABRICKS_TOKEN: dapib1be7a2c69992a23384ea7d30c2b955f
         new-cluster-json: >
           {
             "num_workers": 1,
             "spark_version": "10.4.x-scala2.12",
             "node_type_id": "m6i.large"
           }
